{% set version = "0.8.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dotwhisker
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dotwhisker_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dotwhisker/dotwhisker_{{ version }}.tar.gz
  sha256: d452b9a1d5248f1a4a8f6be791d627367ec0b247b52797bcca617806ca01345c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2 >=2.2.1
    - r-ggstance
    - r-gridextra
    - r-gtable
    - r-parameters
    - r-patchwork
    - r-performance
    - r-purrr
    - r-rlang
    - r-stringr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2 >=2.2.1
    - r-ggstance
    - r-gridextra
    - r-gtable
    - r-parameters
    - r-patchwork
    - r-performance
    - r-purrr
    - r-rlang
    - r-stringr

test:
  commands:
    - $R -e "library('dotwhisker')"           # [not win]
    - "\"%R%\" -e \"library('dotwhisker')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=dotwhisker
  license: MIT
  summary: Quick and easy dot-and-whisker plots of regression results.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: dotwhisker
# Type: Package
# Title: Dot-and-Whisker Plots of Regression Results
# Version: 0.5.0
# Date: 2018-06-27
# Authors@R: c( person("Frederick", "Solt", role = c("aut", "cre"), email = "frederick-solt@uiowa.edu"), person("Yue", "Hu", role = c("aut"), email = "yue-hu-1@uiowa.edu"), person("Oliver", "Keyes", role = "ctb", email = "ironholds@gmail.com"), person("Ben", "Bolker", role = "ctb", email = "bolker@mcmaster.ca"), person("Stefan", "Muller", role = "ctb", email = "mullers@tcd.ie"), person("Thomas", "Leeper", role = "ctb", email = "thosjleeper@gmail.com"))
# Maintainer: Frederick Solt <frederick-solt@uiowa.edu>
# Description: Quick and easy dot-and-whisker plots of regression results.
# Encoding: UTF-8
# BugReports: https://github.com/fsolt/dotwhisker/issues
# Depends: R (>= 3.2.0), ggplot2 (>= 2.2.1)
# Imports: grid, stats, broom, dplyr, stringr, ggstance, rlang, purrr, gtable
# Suggests: mfx, ordinal, tibble, gridExtra, knitr, rmarkdown
# License: MIT + file LICENSE
# LazyData: TRUE
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-06-27 18:19:17 UTC; fredsolt
# Author: Frederick Solt [aut, cre], Yue Hu [aut], Oliver Keyes [ctb], Ben Bolker [ctb], Stefan Muller [ctb], Thomas Leeper [ctb]
# Repository: CRAN
# Date/Publication: 2018-06-27 19:19:32 UTC
